spring:
  devtools:
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/gems_ai
    username: gems
    password: gems
  cloud:
    kubernetes:
      discovery:
        enabled: false
