spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:valkey}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gems_ai}
    username: ${SPRING_DATASOURCE_USERNAME:gems}
    password: ${SPRING_DATASOURCE_PASSWORD:gems}
  cloud:
    kubernetes:
      discovery:
        enabled: true
