spring:
  devtools:
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/eprise_ai
    username: eprise
    password: eprise
  cloud:
    kubernetes:
      discovery:
        enabled: false

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
