spring:
  devtools:
    restart:
      enabled: false
  kafka:
    bootstrap-servers: kafka:9092
services:
  whisper:
    url: ${SERVICES_WHISPER_URL:https://openrouter.ai/api/v1}
    api-key: ${OPENAI_API_KEY:}
ai:
  minio:
    url: ${MINIO_URL:http://minio:9000}
    access-key: ${MINIO_ACCESS_KEY:gems}
    secret-key: ${MINIO_SECRET_KEY:gems-password}
