server:
  port: 8084
spring:
  application:
    name: gems-rag-orchestrator-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        options:
          model: ${SPRING_AI_CHAT_MODEL:openrouter/free}
  cloud:
    kubernetes:
      discovery:
        enabled: true
grpc:
  client:
    retrieval-service:
      address: 'static://localhost:9083'
      negotiation-type: plaintext
