spring:
  devtools:
    restart:
      enabled: true
  cloud:
    kubernetes:
      discovery:
        enabled: false
grpc:
  client:
    retrieval-service:
      address: 'static://localhost:9083'
      negotiation-type: plaintext
