spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gems_ai}
    username: ${SPRING_DATASOURCE_USERNAME:gems}
    password: ${SPRING_DATASOURCE_PASSWORD:gems}
  cloud:
    kubernetes:
      discovery:
        enabled: true
grpc:
  client:
    retrieval-service:
      address: 'dns:///gems-retrieval-service:9083'
      negotiation-type: plaintext
