spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eprise_ai}
    username: ${SPRING_DATASOURCE_USERNAME:eprise}
    password: ${SPRING_DATASOURCE_PASSWORD:eprise}
  cloud:
    kubernetes:
      discovery:
        enabled: false
grpc:
  client:
    retrieval-service:
      address: 'static://localhost:9083'
      negotiation-type: plaintext

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
