apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-service
  namespace: airag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-service
  template:
    metadata:
      labels:
        app: whisper-service
    spec:
      containers:
        - name: whisper-service
          image: ghcr.io/openai/whisper-asr-webservice:latest
          ports:
            - containerPort: 9000
          env:
            - name: ASR_MODEL
              value: base
            - name: ASR_ENGINE
              value: openai_whisper
---
apiVersion: v1
kind: Service
metadata:
  name: whisper-service
  namespace: airag
spec:
  selector:
    app: whisper-service
  ports:
    - port: 8090
      targetPort: 9000
