spring:
  devtools:
    restart:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
ai:
  minio:
    url: http://localhost:9000
    access-key: gems
    secret-key: gems-password
grpc:
  client:
    ocr-service:
      address: 'static://localhost:9086'
      negotiation-type: plaintext
