server:
  port: 8081
spring:
  application:
    name: gems-ai-etl-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
ai:
  chunking:
    strategy: paragraph
    max-segment-size: 1000
    max-overlap-size: 200
grpc:
  client:
    ocr-service:
      address: 'static://localhost:9086'
      negotiation-type: plaintext
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
